#include QMK_KEYBOARD_H


/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */


const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT_planck_mit(KC_Q, KC_W, KC_F, KC_P, KC_G, KC_NO, KC_NO, KC_J, KC_L, KC_U, KC_Y, KC_BSPC, LGUI_T(KC_A), LALT_T(KC_R), LCTL_T(KC_S), LSFT_T(KC_T), KC_D, KC_NO, KC_NO, KC_H, LSFT_T(KC_N), LCTL_T(KC_E), LALT_T(KC_I), LGUI_T(KC_O), KC_Z, KC_X, KC_C, KC_V, KC_B, KC_NO, KC_NO, KC_K, KC_M, KC_COMM, KC_DOT, KC_ENT, KC_NO, KC_NO, KC_ESC, MO(2), KC_BSPC, KC_NO, KC_SPC, MO(1), KC_NO, KC_NO, KC_NO),
	[1] = LAYOUT_planck_mit(KC_EXLM, KC_AT, KC_HASH, KC_DLR, KC_PERC, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_QUOT, KC_DQUO, KC_CIRC, KC_AMPR, KC_ASTR, KC_LPRN, KC_NO, KC_NO, KC_NO, KC_NO, KC_LSFT, KC_LCTL, KC_LALT, KC_LGUI, KC_NO, KC_NO, KC_LCBR, KC_RCBR, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_COMM, KC_DOT, KC_SLSH, KC_NO, KC_NO, KC_NO, KC_RPRN, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO),
	[2] = LAYOUT_planck_mit(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_7, KC_8, KC_9, KC_PLUS, KC_LGUI, KC_LALT, KC_LCTL, KC_LSFT, KC_NO, KC_NO, KC_NO, KC_NO, KC_4, KC_5, KC_6, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_1, KC_2, KC_3, KC_MINS, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_NO, KC_NO, KC_SPC, KC_0, KC_0, KC_NO, KC_NO)
};

// ----- combos -----
const uint16_t PROGMEM combo_single_quote[] = {KC_Q, KC_W, COMBO_END};
const uint16_t PROGMEM combo_double_quote[] = {KC_Y, KC_SEMICOLON, COMBO_END};
const uint16_t PROGMEM combo_backtick[] =     {KC_Z , KC_X, COMBO_END};
const uint16_t PROGMEM combo_tilde[] =        {KC_COMMA, KC_DOT, COMBO_END};
const uint16_t PROGMEM combo_backslash[] =    {KC_Z, KC_V, COMBO_END};
combo_t key_combos[] = {
    COMBO(combo_single_quote, KC_QUOTE),
    COMBO(combo_double_quote, KC_DOUBLE_QUOTE),
    COMBO(combo_backtick,     KC_GRAVE),
    COMBO(combo_tilde,        KC_TILDE),
    COMBO(combo_backslash,    KC_BACKSLASH),
};
